# Generated by Django 5.0.1 on 2025-11-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blessedApp', '0006_alter_reserva_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='qr_codigo',
            field=models.ImageField(blank=True, null=True, upload_to='qr/'),
        ),
    ]
